export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Cadastrar } from './Cadastrar'
export { default as Perfil } from './Perfil'
export { default as Experiencias } from './Experiencias'
export { default as Encontrar } from './Encontrar'