export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Cadastrar } from './Cadastrar'
export { default as Inicio } from './Inicio'
export { default as Experiencias } from './Experiencias'
export { default as Encontrar } from './Encontrar'
export { default as Gatos } from './Gatos'
export { default as Cachorro } from './Cachorros'